# Generated by Django 6.0.5 on 2026-06-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('furniture_type', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
