# Generated by Django 6.0.5 on 2026-06-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('progress', 'In Progress'), ('completed', 'Completed'), ('delivery', 'Out for Delivery')], default='pending', max_length=20),
        ),
    ]
