# Generated by Django 6.0.5 on 2026-06-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
