# Generated by Django 6.0.5 on 2026-06-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
