# Generated by Django 6.0.5 on 2026-06-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('livingroom', 'Living Room'), ('bedroom', 'Bedroom'), ('office', 'Office'), ('cafe', 'Cafe')], max_length=30),
        ),
    ]
