# Generated by Django 5.1.3 on 2026-05-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('sold', 'Sold'), ('custom', 'Custom')], default='ready', max_length=20),
            preserve_default=False,
        ),
    ]
